# Deploy Jekyll site to GitHub Pages
name: Deploy Jekyll site to Pages

on:
  # Runs on pushes to the default branch
  push:
    branches: ["main"]

  # Allows manual trigger from the Actions tab
  workflow_dispatch:

# Set permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4.1" # Not needed if you have a .ruby-version file
          bundler-cache: true # Caches installed gems
          cache-version: 0 # Increment if you need to re-download cached gems

      - name: Setup GitHub Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Debug Base Path
        run: echo "Base Path $BASE_PATH"
        env:
          BASE_PATH: ${{ steps.pages.outputs.base_path }}

      - name: Build Jekyll Site
        run: |
          BASEURL="${{ steps.pages.outputs.base_path }}"
          if [ -z "$BASEURL" ]; then
            BASEURL="/"
          fi
          echo "Using baseurl: $BASEURL"
          bundle exec jekyll build --baseurl "$BASEURL"
        env:
          GITHUB_PAGES: true

      - name: Check _site Directory
        run: |
          ls -la _site  # Debugging step to confirm the _site directory exists

      - name: Upload Jekyll site
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site # Ensure the built Jekyll site is uploaded
          name: github-pages # Explicitly set the artifact name

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@latest
        with:
          name: github-pages
          path: _site # Ensure it extracts to the correct directory

      - name: List downloaded files
        run: ls -la _site # Debugging step to confirm files exist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
